spring:
  profiles:
    active: dev
  application:
    name: gachiganjik-api
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

server:
  address: 0.0.0.0
  port: 8080

logging:
  level:
    com.gachiganjik: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE